# Generated by Django 3.2.13 on 2022-11-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='callnumber',
        ),
    ]
